@startuml diagrama-de-componentes

title Diagrama de Componentes - Sistema de Gestão das Olimpíadas

left to right direction
skinparam componentStyle uml2
skinparam shadowing false
skinparam packageStyle rectangle

package "Interface de Usuário" {

    component TelaCompetições <<UI>>
    component TelaInscricoes  <<UI>>
    component TelaLocais      <<UI>>
    component TelaResultados  <<UI>>
    component TelaRelatorios  <<UI>>

}

package "Módulo de Competições" {

    component ControladorCompeticao

    interface ICompeticao as IComp

    ControladorCompeticao - IComp : fornece
}

package "Módulo de Inscrições" {

    component ControladorInscricao

    interface IInscricao as IInscricao

    ControladorInscricao - IInscricao : fornece
    ControladorInscricao ..> IComp : consulta competição
}

package "Módulo de Alocação" {

    component ControladorAlocacao

    interface IAlocacao as IAloc

    ControladorAlocacao - IAloc : fornece
    ControladorAlocacao ..> IComp : valida horários
}

package "Módulo de Resultados" {

    component ControladorResultado

    interface IResultado as IResult

    ControladorResultado - IResult : fornece
    ControladorResultado ..> IComp : obtém competição
}

package "Módulo de Relatórios" {

    component GeradorRelatorio

    interface IRelatorio as IRel

    GeradorRelatorio - IRel : fornece

    GeradorRelatorio ..> IResult : consulta resultados
    GeradorRelatorio ..> IInscricao : consulta inscrições
}

package "Persistência" {

    database "Banco de Dados" as BD

}



TelaCompetições --> ControladorCompeticao : gerenciar competições
TelaInscricoes  --> ControladorInscricao  : realizar inscrição
TelaLocais      --> ControladorAlocacao   : alocar locais
TelaResultados  --> ControladorResultado  : registrar resultados
TelaRelatorios  --> GeradorRelatorio      : emitir relatórios



ControladorCompeticao ..> BD : salvar/consultar
ControladorInscricao  ..> BD : salvar/consultar
ControladorAlocacao   ..> BD : salvar/consultar
ControladorResultado  ..> BD : salvar/consultar
GeradorRelatorio      ..> BD : consultar

@enduml
