@startuml DiagramaDeClasses_Olimpiadas

skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #2C3E50
skinparam arrowColor #2C3E50
skinparam arrowThickness 1.5
skinparam shadowing false

enum TipoMedalha {
  OURO
  PRATA
  BRONZE
}

enum StatusCompeticao {
  AGENDADA
  EM_ANDAMENTO
  FINALIZADA
  CANCELADA
}

enum Modalidade {
  NATACAO
  ATLETISMO
  GINASTICA
  JUDO
  VOLEI
  FUTEBOL
}

class Local {
  +idLocal    : int
  +nomeLocal  : String
  +cidade     : String
  +capacidade : int
  +verificarDisponibilidade(data: Date, horario: Time): bool
}

class Competicao {
  +idCompeticao : int
  +data         : Date
  +horario      : Time
  +status       : StatusCompeticao
  +modalidade   : Modalidade
  +cadastrarCompeticao(): void
  +cancelarCompeticao(): void
  +getInformacoes(): String
}

class Atleta {
  +idAtleta         : int
  +nome             : String
  +numeroCredencial : String
  +dataNascimento   : Date
  +inscreverEmCompeticao(Competicao): void
  +getInformacoes(): String
}

class Pais {
  +idPais   : int
  +nomePais : String
  +totalOuro()   : int
  +totalPrata()  : int
  +totalBronze() : int
  +gerarRelatorioMedalhas(): String
}

class Resultado {
  +idResultado  : int
  +atletaOuro   : String
  +atletaPrata  : String
  +atletaBronze : String
  +registrarResultado(): void
  +getVencedor(): String
}

class Medalha {
  +idMedalha   : int
  +dataEntrega : Date
  +tipo        : TipoMedalha
  +modalidade  : Modalidade
  +getDescricao(): String
}

class InscricaoCompeticao {
  +dataInscricao   : Date
  +statusInscricao : String
  +confirmarInscricao(): void
  +cancelarInscricao(): void
}

' COMPOSIÇÃO
Local      "1"    *-- "0..*" Competicao : contém
Competicao "1"    *-- "0..1" Resultado  : gera
Pais       "1"    *-- "0..*" Medalha    : acumula

' AGREGAÇÃO
Pais      "1" o-- "1..*" Atleta : representa
Resultado "1" o-- "3"    Atleta : classifica

' ASSOCIAÇÃO com classe associativa
Atleta     "1..*" -- "1..*" Competicao
InscricaoCompeticao . Atleta
InscricaoCompeticao . Competicao

' ENUMS
Competicao ..> StatusCompeticao : usa
Competicao ..> Modalidade       : usa
Medalha    ..> TipoMedalha      : usa
Medalha    ..> Modalidade       : usa

@enduml